### ISSUE TITLE
[BUG] Hosted centroid interactions no longer working on centroid hover

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-explorer#100]
From seve: At some point, we broke the functionality attached to centroid labels, where hovering over the label itself no longer dilates the cells or category labels on the left sidebar.

I think this has to do with a typo that is semi fixed, breaking some places, but not others.

See screen recording here: https://github.com/chanzuckerberg/cellxgene/issues/2454

**Comment by signechambers1** [comment]
This is now fixed

**Comment by seve** [comment]
https://user-images.githubusercontent.com/8716829/146468081-9ac76b88-e85e-4637-ad9e-2188666c1f32.mov

Still seeing this on prod and dev @signechambers1

**Comment by signechambers1** [comment]
My bad, this is still an issue. It is fixed on desktop but not hosted.
